### ISSUE TITLE
Pre compiled version for windows using node-pre-gyp

### ISSUE THREAD

**Issue by megastef** [dainis/node-gcstats#18]
Windows users require a complicated setup for Visual Studio VC++. It would be very helpful to have gc-stats as pre-compiled module e.g. using http://www.appveyor.com/  and https://github.com/mapbox/node-pre-gyp

**Comment by dainis** [comment]
Sorry, 

But I don't have any windows boxes to test and develope for windows

PR is welcome

**Comment by megastef** [comment]
:) That's why I asked -  http://www.appveyor.com/  provides the windows boxes.

**Comment by robrich** [comment]
Need help with this?

**Comment by megastef** [comment]
@robrich +1 for help :)

**Comment by gabrielcsapo** [comment]
Is there a move to have compiled binaries for all archs?

**Comment by szdavid92** [comment]
@gabrielcsapo We have a fork of this lib which we are keeping up to date https://github.com/RisingStack/node-gcstats . We host binaries and use node-pre-gyp for automating this. Currently we do not build for Windows though.

**Comment by megastef** [comment]
@dainis is the problem solved with introducing appvyeor file in the repository? Sorry, i don't have windows to check...

**Comment by dainis** [comment]
@megastef windows has prebuilt binaries, MacOs still doesn't have

**Comment by otisg** [comment]
@dainis should we then close this and open a new ticket for MacOS binaries?

**Comment by spmiller** [comment]
FYI -- v1.4.0 with Node v12 is missing Windows binaries because the build failed:
https://ci.appveyor.com/project/dainis/node-gcstats/builds/24916323

v1.5.0 looks like it will be ok once #49 is resolved.
https://ci.appveyor.com/project/dainis/node-gcstats/builds/33597418

On MacOS support (which I agree should be tracked in a new ticket), @paulrutter and I recently added support for native binaries in [node-oom-heapdump](https://github.com/blueconic/node-oom-heapdump) using Github Actions. It would be possible to create a workflow that is triggered by a publish, which then builds on MacOS like Travis/Appveyor.

**Comment by robross0606** [comment]
Is this ever going to be fixed for 1.4.0?
